services:
  gadgets-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 25053:3000
    platform: linux/amd64

  gadgets-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 25054:3000
    depends_on:
      - gadgets-db
    platform: linux/amd64

  gadgets-db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: gadgets
    platform: linux/amd64

volumes:
  postgres-data:
