services:
  chall:
    environment:
      - FLAG=cuhk25ctf{d-s0lution_2_not_enough_REV_chall_IDEAs_iS_2_reWriTe_0ld_prOblEMs_2n_RUST}
    ports:
      - "24066:3000"
    build:
      context: ..
      dockerfile: deploy/Dockerfile
