apiVersion: v1
kind: Config
clusters:
- cluster:
    server: https://2217560D8A76DCD08A204B66621B75E4.gr7.us-east-1.eks.amazonaws.com
  name: ds-kinf-s
contexts:
- context:
    cluster: ds-kinf-s
    namespace: infinity-castle
    user: player
  name: ds-kinf-s
current-context: ds-kinf-s
users:
- name: player
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6Il8zMjRJMmlad2s2ZEtCTGtQZFVoOHExQVBqR0dqTFBRVjlrVVVBb1FHRlEifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJpbmZpbml0eS1jYXN0bGUiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoicGxheWVyLXRva2VuIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6InBsYXllciIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImE5ZjcyNjFlLTU4ZjYtNDg3OS1hYzMxLTE1ZDc3NWJjYWJlYSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDppbmZpbml0eS1jYXN0bGU6cGxheWVyIn0.nThjOLF4-cSwKV29AOmPjLyF3_kyvLcM5EvpR_D-RkBxpwX02zC_4TRXV4GBY7TvpS3nM73D82B-PPjLPy_EkY7JdAzoeIbEI-YdU0bHaxX6qZ2bEy95FdbUym3uxzjQCEuwpJuseZoue4m8SqZfn9w7eAZktjthDBB4UiLlB4F8jfWp1q0QYXaOlNy_LkUXA_fqOGbLdRakRZQIfrBgdBUuSn1imfITb-GjzIib3fR2KXb4MkcOVfC36C9f1xLiXKskh0CNQMi0yUMuOhdUL8_hRv2wmeIwR6iFJmFhBkxpw2HdZ007vsfR8Nvp6NKMsX5etL1Xw4DeLICoO1E2Tg
